---
title: "frankenrockt"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
social: menu
source_code: embed
---

```{r rmd_settings_code, include=FALSE}
knitr::opts_chunk$set(include=FALSE)
```

```{r libs}
library(knitr)
library(flexdashboard)
library(dplyr)
library(ggplot2)
library(sf)
library(mapview)
library(leaflet)
```

```{r test_data}
tst_dat1 = data.frame(name = "Swedish Curtains", 
                     motto = "Hardrockband from Münchsteinach fighting to hold the rythm", 
                     genre = "Hard Rock", 
                     from = 2006, 
                     to = 2020, 
                     song = paste0("can't stop: <a href=", "https://www.youtube.com/watch?v=j37Ii20Ddo4",">", "https://www.youtube.com/watch?v=j37Ii20Ddo4", "</a>"), 
                     x = 10.59689555556497, 
                     y = 49.63753461701194)
tst_dat2 = data.frame(name = "Die Verstimmten Klimexperten", 
                     motto = "Four from the future.", 
                     genre = "Hard Rock", 
                     from = 2004, 
                     to = 2010, 
                     song = "not online", 
                     x = 10.621313357566068, 
                     y = 49.58177091487892)
tst_dat = rbind(tst_dat1, tst_dat2)
frankenrockt = sf::st_as_sf(x = tst_dat, coords = c("x", "y"), crs = st_crs(4326))
mv = mapview(x = frankenrockt, label = frankenrockt$name)
```

```{r map, include=TRUE}
mv
```

